language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"

  - "iojs"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "iojs"

install:

  - npm install -g gulp
  - npm run setup

script:

  - gulp less
  - gulp less-hint
